// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'db/dictionary.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 4600129934155544425),
      name: 'Dicionary',
      lastPropertyId: const IdUid(3, 5135385939418517847),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 679921062470274717),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 5778085441352051698),
            name: 'uz',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 5135385939418517847),
            name: 'ing',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 4600129934155544425),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    Dicionary: EntityDefinition<Dicionary>(
        model: _entities[0],
        toOneRelations: (Dicionary object) => [],
        toManyRelations: (Dicionary object) => {},
        getId: (Dicionary object) => object.id,
        setId: (Dicionary object, int id) {
          object.id = id;
        },
        objectToFB: (Dicionary object, fb.Builder fbb) {
          final uzOffset = fbb.writeString(object.uz);
          final ingOffset = fbb.writeString(object.ing);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uzOffset);
          fbb.addOffset(2, ingOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Dicionary(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              uz: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              ing: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [Dicionary] entity fields to define ObjectBox queries.
class Dicionary_ {
  /// see [Dicionary.id]
  static final id = QueryIntegerProperty<Dicionary>(_entities[0].properties[0]);

  /// see [Dicionary.uz]
  static final uz = QueryStringProperty<Dicionary>(_entities[0].properties[1]);

  /// see [Dicionary.ing]
  static final ing = QueryStringProperty<Dicionary>(_entities[0].properties[2]);
}
